server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    location = /healthz.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/healthz.php;
        fastcgi_pass app:9000;
    }

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_pass app:9000;
    }

    location ~ /\. {
        deny all;
    }
}
